language: java
jdk:
- openjdk11
branches:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_e558ecafaec6_key -iv $encrypted_e558ecafaec6_iv
  -in properties.tar.enc -out properties.tar -d
- echo "압축 풀기 전"
- tar -xvf properties.tar
- pwd
- ls
- cp application.properties src/main/resources
- cp application-oauth.properties src/main/resources
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
before_deploy:
- mkdir -p before-deploy
- cp scripts/*.sh before-deploy/
- cp appspec.yml before-deploy/
- cp build/libs/*.war before-deploy/
- pwd
- ls
- echo "copy end"
- cd before-deploy && zip -r before-deploy *
- cd ../ && mkdir -p deploy
- echo "cd end"
- pwd
- ls -al
- mv before-deploy/before-deploy.zip deploy/zerogreen.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: zerogreen-build
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true
  on:
    branch: main
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: zerogreen-build
  key: zerogreen.zip
  bundle_type: zip
  application: zerogreen-webservice
  deployment_group: zerogreen-webservice-group
  region: ap-northeast-2
  wait-until-deployed: true
  on:
    branch: main
notifications:
  email:
    recipients:
    - dylee0568@gmail.com
