# 언어와 jdk의 버전을 지정한다.
language: java
jdk:
  - openjdk11

# 어느 브랜치가 push 될 때 수행할지 지정한다. 
# 오직 main 브랜치가 push될 때 수행하도록 지정하였다.
branches:
  only:
    - main

# 빌드 전에 gradlew의 권한을 추가한다.
before_install:
  - chmod +x gradlew
  - cp /home/ec2-user/app/application.properties /home/ec2-user/app/step1-1/zerogreen/src/main/resources
  - cp /home/ec2-user/app/application-oauth.properties /home/ec2-user/app/step1-1/zerogreen/src/main/resources
  - cp /home/ec2-user/app/application-real-db.properties /home/ec2-user/app/step1-1/zerogreen/src/main/resources

# Travis CI 서버의 Home
# gradle을 통하여 의존성을 받게 되면 이를 캐시하여 배포할 때 마다 다시 받지 않도록 설정한다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# main 브랜치에 push 되면 수행되는 명령어이다. 
# 프로젝트 내에 권한이 추가된 gradlew를 활용하여 clean, build를 진행한다.
script:
  - "./gradlew clean build"
  - cp /home/ec2-user/app/step1-1/zerogreen/build/libs/*.war /home/ec2-user/app/step1-1/
  - cd /home/ec2-user/app/step1-1/
  - mv eco-0.0.1-SNAPSHOT.war zerogreen.war
  - mv zerogreen.war /home/ec2-user/apache-tomcat-9.0.60/webapps
  - rm -r -f /home/ec2-user/apache-tomcat-9.0.60/webapps/zerogreen
  - cd /home/ec2-user/apache-tomcat-9.0.60/bin
  - unset CATALINA_HOME
  - ./shutdown.sh
  - ./startup.sh

# CI 실행 완료 시 작성한 이메일로 알람
notifications:
  email:
    recipients:
      - dylee0568@gmail.com