language: java
jdk:
- openjdk11
branches:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_2f692484526a_key -iv $encrypted_2f692484526a_iv
  -in application.properties.enc -out application.properties -d
- openssl aes-256-cbc -K $encrypted_b846c1a3db1c_key -iv $encrypted_b846c1a3db1c_iv
  -in application-oauth.properties.enc -out application-oauth.properties -d
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
before_deploy:
- mkdir -p before-deploy
- cp scripts/*.sh before-deploy/
- cp appspec.yml before-deploy/
- cp build/libs/*.war before-deploy/
- cd before-deploy && zip -r before-deploy *
- cd ../ && mkdir -p deploy
- mv before-deploy/before-deploy.zip deploy/zerogreen.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: zerogreen-build
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true
  on:
    branch: main
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: zerogreen-build
  key: zerogreen.zip
  bundle_type: zip
  application: zerogreen-webservice
  deployment_group: zerogreen-webservice-group
  region: ap-northeast-2
  wait-until-deployed: true
  on:
    branch: main
notifications:
  email:
    recipients:
    - dylee0568@gmail.com
