version: 0.0 # CodeDeploy 버전을 명시한다.
os: linux
files:
  - source:  / # 전체 파일을 나타낸다.
#    destination: /home/ec2-user/app/step3/zip/ # source로 지정된 전체 파일이 받을 위치이다.
    destination: /home/ec2-user/app/step2/zip/ # source로 지정된 전체 파일이 받을 위치이다.
    overwrite: yes # 기존 파일들이 있으면 덮어 쓸지를 결정한다.
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링부트 시작
      timeout: 60
      runas: ec2-user
#  AfterInstall:
#    - location: stop.sh # 엔진 엑스에 연결되어 있지 않은 스프링부트 종료
#      timeout: 60
#      runas: ec2-user
#  ApplicationStart:
#    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링부트 시작
#      timeout: 60
#      runas: ec2-user
#  ValidateService:
#    - location: health.sh # start.sh로 실행시킨 프로젝트가 정상 실행했는지 확인
#      timeout: 60
#      runas: ec2-user